### ISSUE TITLE
Is that possible to add new language? 

### ISSUE THREAD

**Issue by wangjun-sh** [ffes/nppsnippets#47]
Is that possible to allow user add new language? 

In the library option, there is a popup window "Edit languages". However there is no option to add new language.

In the repo, this SQL says "Language" table is only for reference: 
    https://github.com/ffes/nppsnippets/blob/master/misc/Languages.sql

thanks, John

**Comment by ffes** [comment]
If you mean that you want support for UDL, that seems to be impossible at the moment. See #43 for support on UDL.

For all other languages NppSnippets relies on the languages that are programmed into N++ itself and there is nothing I can do about. So adding a language to the database doesn't help because N++ won't recognize the language in the file and there will be no `LangType` attached to that file. And that N++ builtin `LangType` is the key for the language support that NppSnippets uses.

**Comment by wangjun-sh** [comment]
Yes I mean UDL (user defined language). 
- John

**Comment by ffes** [comment]
> Yes I mean UDL (user defined language).

Thanks for the feedback.  Therefore, I close this as a dup of #43
